TrajectoryPlannerROS:
  
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.2
  
  escape_vel: -0.2

  acc_lim_theta: 2.4
  acc_lim_x: 1.2
  acc_lim_y: 1.2
  
  meter_scoring: true
  controller_frequency: 10.0
  
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.05
  
  holonomic_robot: false