map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.0

transform_tolerance: 0.4

#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
footprint: [[-0.22, -0.20], [-0.22, 0.20], [0.22, 0.20], [0.22, -0.20]]

#robot_radius: ir_of_robot
inflation_radius: 0.4

observation_sources: laser_scan_sensor # point_cloud_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}